### ISSUE TITLE
Plugin metadata changes

### ISSUE THREAD

**Issue by arnellebalane** [idpass/smartscanner-cordova#8]
## Current Behaviour

Plugin metadata still references files and package ID for the MLKit plugin.

## Expected Behaviour

Plugin metadat should now reference the new SmartScanner files and package ID.

## Steps to Reproduce the Problem

1. `npm install -D @idpass/smartscanner-cordova`
1. `cordova plugin add @idpass/smartscanner-cordova`

```bash
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-impactlabs-mlkit': CordovaError: Uh oh!
```

## Context

- Version: `0.3.0-beta.1`
- Platform: Android
- Cordova version: `9.0.0 (cordova-lib@9.0.1)`

**Comment by rjmangubat23** [comment]
Already applied changes in latest version `v0.3.6`
